# Generated by Django 3.0.3 on 2020-02-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
