# Generated by Django 3.0.3 on 2020-02-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20200227_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quotes',
            new_name='Quote',
        ),
    ]
