# Generated by Django 3.0.3 on 2020-03-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20200330_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plunge',
            fields=[
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=2000, null=True)),
            ],
        ),
    ]
