# Generated by Django 3.0.3 on 2020-02-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20200227_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote_Rumi',
            fields=[
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Quotes_Rumi',
            },
        ),
    ]
