# Generated by Django 3.0.3 on 2020-03-31 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_plunge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plunge',
            name='date',
        ),
        migrations.AlterField(
            model_name='plunge',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plunge',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Plunge_item',
            fields=[
                ('more', models.TextField(max_length=1000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=2000, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Plunge')),
            ],
        ),
    ]
