# Generated by Django 3.0.3 on 2020-02-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_quote_rumi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote_Rumi1',
            fields=[
                ('quote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='entries.Quote')),
                ('text_Rumi', models.TextField()),
                ('date_Rumi', models.DateTimeField(auto_now_add=True)),
                ('id_Rumi', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Quotes_Rumi',
            },
            bases=('entries.quote',),
        ),
        migrations.DeleteModel(
            name='Quote_Rumi',
        ),
    ]
