# Generated by Django 3.0.3 on 2020-03-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20200331_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plunge',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Plunge_item',
        ),
    ]
