# Generated by Django 3.0.3 on 2020-02-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20200227_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quote_Rumi1',
            new_name='Quote_child',
        ),
        migrations.AlterModelOptions(
            name='quote_child',
            options={'verbose_name_plural': 'Quotes_<django.db.models.query_utils.DeferredAttribute object at 0x000000BA782AA820>'},
        ),
        migrations.RenameField(
            model_name='quote_child',
            old_name='date_Rumi',
            new_name='date_child',
        ),
        migrations.RenameField(
            model_name='quote_child',
            old_name='id_Rumi',
            new_name='id_child',
        ),
        migrations.RenameField(
            model_name='quote_child',
            old_name='text_Rumi',
            new_name='text_child',
        ),
    ]
