# Generated by Django 3.0.3 on 2020-02-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20200227_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mooji',
            fields=[
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': "Mooji's Quotes",
            },
        ),
        migrations.CreateModel(
            name='Rumi',
            fields=[
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': "Rumi's Quotes",
            },
        ),
        migrations.DeleteModel(
            name='Quote_child',
        ),
    ]
