# Generated by Django 3.0.3 on 2020-03-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_topics_topics_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
        migrations.RenameModel(
            old_name='Topics_items',
            new_name='Topics_item',
        ),
    ]
