# Generated by Django 3.0.3 on 2020-03-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_auto_20200312_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics_item',
            new_name='Topic_item',
        ),
    ]
