# Generated by Django 3.0.3 on 2020-03-16 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_auto_20200312_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='text',
        ),
    ]
