# Generated by Django 3.0.3 on 2020-03-17 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0016_auto_20200316_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote_item',
            fields=[
                ('more', models.TextField(max_length=1000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Mooji',
        ),
        migrations.DeleteModel(
            name='Rumi',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='date',
        ),
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='quote_item',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Quote'),
        ),
    ]
